on:
  push:
    branches:
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: 'ghcr.io/kyle-verhoog/python-images/all:${{ github.sha }}'
          platforms: 'linux/amd64,linux/arm64/v8'
          context: ./images/all
